<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>E2E - Login - Order</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5af994d7-777e-4705-b2db-93e1d1608d47</testSuiteGuid>
   <testCaseLink>
      <guid>a951de34-cdd4-4cf1-9e6a-4fa47895a24b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MainPage/TC_OpenURL</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>55900dc3-8607-4e0f-81d6-7643ff97f57b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/MainPage/TC_OpenPageMasuk</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>d9d082f2-cbf1-4955-bf09-fa7db15fcc78</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/LoginPage/TC_LoginNegative</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53deaab9-6377-4825-b67b-2be7d86892b9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27c0bc3e-f287-4a1f-887b-ba5c5c963cf8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cedc317d-13e4-43d6-aa3d-c1920a8ac70a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21e15cd8-f9ff-49bb-b8c3-89b5ad2db230</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/LoginPage/TC_LoginPositive</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc965d5c-2bfd-4718-99a2-16ec305b23a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e814828f-8efc-4a88-98ef-e59ecb19c176</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1deeeb75-eb84-4340-b21e-d96eba8f3dcc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ProductOrderPage/Roblox/TC_Order50KwithQRIS</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57b2c78f-3729-42a3-aabc-cfc808931fe5</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
